### PR TITLE
Midi MPU401 experimental work

### PR DESCRIPTION
**Pull request by squidrpi**
Wonder if you could have a browse through my changes. I'm trying to implement MIDI MPU401 support. I've sort of got it working as MIDI plays on my MT32 but the notes are garbled and volumes are set wrong. Multiple channels play but not correctly. Some of the melody sounds correct at times. I used the ao486 MPU/UART files and integrated them into ddr_186.v. Initialisation looks correct as Monkey, Atlantis, DOTT start OK when using the Roland option.

My clock timings are probably completely wrong (never get the hang of them). Possibly though the data isn't being fed correctly from the CPU IO. I'm confused about the "IORQ && CPU_CE" and have left them out of CS. Either that or there's no hope for this to work. Only experimental work but perhaps it could work?

stp2.stp setup for debug and OPL3 disabled.

### CODE REVIEW

**Comment by gyurco** [comment]
Uhh, lot of code there. But if you're doing asynchronous clock domain crossings (like going from cpu_clk to mpu_clk), you must use synchronisers, dual-clock fifos and such constructs. It's better to avoid this kind of coding in new designs. Otherwise you'll get pure instability.

**Comment by gyurco** [comment]
Or an idea: you can use a DCFIFO, one side is writing data to the fifo in the cpu clock domain, the other side is reading it in the mpu clock domain.

**Comment by squidrpi** [comment]
Not a lot of code changed just the 16550 UART (uart directory) has been added from ao486. 16550 is asynchronous I believe. https://opencores.org/projects/a_vhd_16550_uart
https://opencores.org/websvn/filedetails?repname=a_vhd_16550_uart&path=%2Fa_vhd_16550_uart%2Fweb_uploads%2Fvhdl_16550_uart_2_2.pdf

**Comment by gyurco** [comment]
Ahh, uploading zip snapshots into the svn - nice abuse of a version control system. However my concern is valid: data from the cpu is created in the cpu_clk domain, you need correctly transfer it to the mpu_clk domain.

**Comment by gyurco** [comment]
Ok, I see that br_clk is used only in the baud rate generator, probably implemented correctly to sync to the main clock. However you cannot omit IORQ from CS, as it would be erroneously activate CS when the bus has the MPU address, but the CPU does something else. Maybe CE is not needed, the semantics of the CS should be investigated, when it's active: negative edge, positive edge, when WR is needed, etc...

**Comment by gyurco** [comment]
I don't really understand this:
https://github.com/gyurco/Next186/pull/6/commits/21122d5df1d1f50c216013fd6520d8324a47cbb9#diff-00a4358fda6d3f6c64ae060dee53d6cc18818c75f14296ee480926867eb651f1R34
Why not pass CE and address directly to the uart module? Actually why the wrapper is needed?

And this:
https://github.com/gyurco/Next186/pull/6/commits/21122d5df1d1f50c216013fd6520d8324a47cbb9#diff-00a4358fda6d3f6c64ae060dee53d6cc18818c75f14296ee480926867eb651f1R71
If you don't use CPU_CE for CS, then when read_ack=1, it returns FE, then immediately (on the next cycle), it will return 'data'. Effectively the CPU will never see FE. If this wrapper really needed, then it should use the same semantics on CS as the UART module.

**Comment by squidrpi** [comment]
Thanks for the tips.
The wrapper is needed as the MPU has a command/status port 331h (address==1) and a data port 330h (address==0). Only the data port will be fed to the UART. The wrapper sets the MPU into certain "modes", with FF reset the MPU, 3F set the MPU into dumb/uart mode. We're only interested in uart mode.
http://midi.teragonaudio.com/tech/mpu.htm

**Pull request closed without merging**
