### PR TITLE
Update Next186_CPU.v

### PR DESCRIPTION
**Pull request by spark2k06**
* FLUSH over the instruction cache in memory MOVs
* Same behavior as an 8086/80186 with PUSH SP, and thus avoid the work around proposed by jepalza

In fact, not only does the **Turbo Debugger** no longer hang and it is recognized correctly, it is also correctly recognized by other programs such as **CheckIT** that previously detected a **286** 

image

### CODE REVIEW

**Comment by gyurco** [comment]
Thanks, let's try it.

**Comment by gyurco** [comment]
Unfortunately this prevents the fdxms286.sys XMS driver to work. Is there any replacement?

**Comment by spark2k06** [comment]
> Unfortunately this prevents the fdxms286.sys XMS driver to work. Is there any replacement?

I did not know, undo the changes in that case if you consider it convenient. I use it in my version of Next186 for PCXT with CGA and EMS memory instead of XMS: 

https://github.com/spark2k06/next186lite_graphics_gremlin

Right now I can't think of another alternative for the Mist and VGA version.

More info:

https://misterfpga.org/viewtopic.php?t=3682

**Comment by spark2k06** [comment]
> Unfortunately this prevents the fdxms286.sys XMS driver to work. Is there any replacement?

I have patched the driver so that it can be used in this version of **Next186**, just replace **stc** with **clc** in this function:

push_sp

I have taken the opportunity to change the strings **286** to **186**:

push_sp_2

And finally I have renamed the file to **fdxms186.sys**, here I leave it available:

[Download fdxms186.sys](https://mega.nz/file/XUoWyTLI#M99dMH-kuM7F_-ssheF9fcXPVH1wQZfqkQ7iwykbshA)

**Comment by gyurco** [comment]
Thanks! That worked.
Now only EMU386 complains:
ERROR: PC/AT with 80186/80286 processor required.

**Comment by spark2k06** [comment]
> Thanks! That worked.
> Now only EMU386 complains:
> ERROR: PC/AT with 80186/80286 processor required.

Give me the version you are using and I will fix it. Would it be this?:

https://survpc.tripod.com/emu386/download.htm

**Comment by gyurco** [comment]
Yes, it is. 1.34beta1

**Comment by spark2k06** [comment]
> Thanks! That worked. Now only EMU386 complains: ERROR: PC/AT with 80186/80286 processor required.

Try this:

[EMM386ST.EXE](https://mega.nz/file/DQh3gCza#UlznaF43G37Q6LCsdRKO3wo1g7ofybF3DEio5Zp-z8I)

**Comment by gyurco** [comment]
Good, EMU386 starts now.
~Colonization however not :(
It freezes just after starting. Previously frozen at the beginning of the game.~

Upd.: sorry, false alarm

**Pull request merged**
